# Generated by Django 4.2.30 on 2026-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='admin', max_length=20),
        ),
    ]
