# Generated by Django 4.2.30 on 2026-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_fix_role_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_brought_forward',
            field=models.BooleanField(default=False, help_text='Payment brought forward from previous period'),
        ),
    ]
