# Generated by Django 4.2.30 on 2026-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_add_beneficiary_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Beneficiary',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='client_type',
            new_name='beneficiary_type',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client',
            new_name='beneficiary',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='beneficiary',
        ),
        migrations.RenameField(
            model_name='openingbalance',
            old_name='client',
            new_name='beneficiary',
        ),
        migrations.RenameField(
            model_name='beneficiaryhistory',
            old_name='client',
            new_name='beneficiary',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('private', 'Private'), ('communal', 'Communal')], max_length=20),
        ),
    ]
