# Generated by Django - manually created to fix recipient_client rename

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_auto_20260429_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationlog',
            old_name='recipient_client',
            new_name='recipient_beneficiary',
        ),
    ]
