# Generated by Django 4.2.30 on 2026-05-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_app', '0006_rename_communicationlog_recipient_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('private', 'Private'), ('communal', 'Communal')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-sent_at'], name='accounting__sender__6764c3_idx')],
            },
        ),
    ]
