# Generated by Django 4.2.30 on 2026-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_alter_budget_options_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetline',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='notes',
        ),
        migrations.AddField(
            model_name='budgetline',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
