# Generated by Django 4.2.30 on 2026-05-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_remove_budgetline_amount_remove_budgetline_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
