# Generated by Django 4.2.30 on 2026-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_alter_budget_options_remove_budget_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='header_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
    ]
