# Generated by Django 5.2.3 on 2026-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0014_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('caption', models.CharField(blank=True, help_text='Short caption explaining the picture', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
