# Generated by Django 5.2.3 on 2026-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0015_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0984e3', help_text='Primary color (hex code like #0984e3)', max_length=7)),
                ('secondary_color', models.CharField(default='#00b894', help_text='Secondary color (hex code like #00b894)', max_length=7)),
                ('hero_gradient_start', models.CharField(default='#0f1923', help_text='Hero section gradient start color', max_length=7)),
                ('hero_gradient_mid', models.CharField(default='#1a2a3a', help_text='Hero section gradient middle color', max_length=7)),
                ('hero_gradient_end', models.CharField(default='#0984e3', help_text='Hero section gradient end color', max_length=7)),
                ('navbar_bg', models.CharField(default='#0f1923', help_text='Navbar background color', max_length=7)),
                ('section_bg_light', models.CharField(default='#f5f6fa', help_text='Light section background color', max_length=7)),
                ('text_primary', models.CharField(default='#1e272e', help_text='Primary text color', max_length=7)),
                ('text_secondary', models.CharField(default='#636e72', help_text='Secondary text color', max_length=7)),
                ('cta_gradient_start', models.CharField(default='#0984e3', help_text='CTA section gradient start', max_length=7)),
                ('cta_gradient_end', models.CharField(default='#00b894', help_text='CTA section gradient end', max_length=7)),
                ('whatsapp_color', models.CharField(default='#25D366', help_text='WhatsApp icon color', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Use these settings (only one should be active)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
