# Generated by Django 5.2.3 on 2026-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_landingpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_dashboard',
            field=models.BooleanField(default=True, help_text='Can access the dashboard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_management',
            field=models.BooleanField(default=False, help_text='Can access management section (schemes, trustees, etc.)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_settings',
            field=models.BooleanField(default=False, help_text='Can access system settings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_communicate',
            field=models.BooleanField(default=False, help_text='Can send communications (SMS/WhatsApp)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_beneficiaries',
            field=models.BooleanField(default=False, help_text='Can delete beneficiaries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_budgets',
            field=models.BooleanField(default=False, help_text='Can delete budgets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_expenses',
            field=models.BooleanField(default=False, help_text='Can delete expenses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_invoices',
            field=models.BooleanField(default=False, help_text='Can delete invoices'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_payments',
            field=models.BooleanField(default=False, help_text='Can delete payments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_beneficiaries',
            field=models.BooleanField(default=False, help_text='Can edit beneficiaries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_budgets',
            field=models.BooleanField(default=False, help_text='Can create/edit budgets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_employees',
            field=models.BooleanField(default=False, help_text='Can manage employees'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_expenses',
            field=models.BooleanField(default=False, help_text='Can create/edit expenses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_invoices',
            field=models.BooleanField(default=False, help_text='Can create/edit invoices'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_journal',
            field=models.BooleanField(default=False, help_text='Can create/edit journal entries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_payments',
            field=models.BooleanField(default=False, help_text='Can record payments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export_reports',
            field=models.BooleanField(default=False, help_text='Can export reports'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can manage users'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_beneficiaries',
            field=models.BooleanField(default=True, help_text='Can view beneficiaries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_budgets',
            field=models.BooleanField(default=False, help_text='Can view budgets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_employees',
            field=models.BooleanField(default=False, help_text='Can view employee records'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_expenses',
            field=models.BooleanField(default=True, help_text='Can view expenses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_invoices',
            field=models.BooleanField(default=True, help_text='Can view invoices'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_journal',
            field=models.BooleanField(default=False, help_text='Can view journal entries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_payments',
            field=models.BooleanField(default=True, help_text='Can view payments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=True, help_text='Can view reports'),
        ),
    ]
