# Generated by Django 5.2.3 on 2026-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0017_userprofile_can_access_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_content',
            field=models.TextField(default='Nkula Water Users Association (WUA) is a community-based institution established in 2013 under the Government of Malawi with financial support from the African Development Bank (ADB). Our purpose is to empower communities to take full responsibility in water management and support community development initiatives.\n\nWe work with local leaders and community members to ensure water schemes are properly managed, protected, and maintained for the benefit of all.', help_text='About section paragraphs (use \\n\\n for new paragraphs)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_subtitle',
            field=models.CharField(default='Who We Are', help_text='About section subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_title',
            field=models.CharField(default='About Us', help_text='About section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='contact_email',
            field=models.CharField(default='nkulawuamw@gmail.com', help_text='Contact email', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='contact_phone',
            field=models.CharField(default='+265 982 960 373', help_text='Contact phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='contact_whatsapp',
            field=models.CharField(default='+265 982 960 373', help_text='WhatsApp number (with country code, no +)', max_length=30),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='contact_whatsapp_raw',
            field=models.CharField(default='265982960373', help_text='WhatsApp number raw format for link (e.g. 265982960373)', max_length=30),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='cta_description',
            field=models.TextField(default='Nkula WUA invites partners, community members, and stakeholders to support the mission of providing safe and sustainable water. Together we can protect our water sources and improve lives.', help_text='Call-to-action description'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='cta_title',
            field=models.CharField(default='Join Us in Building Sustainable Water Access', help_text='Call-to-action heading', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='footer_text',
            field=models.TextField(default='Nkula Water Users Association (WUA)\nGood and Quality Water for All.\n2026 Nkula Water Users Association. All Rights Reserved.\nDesigned for Community Water Development and Sustainability.', help_text='Footer lines (one per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_description',
            field=models.TextField(default='Nkula Water Users Association is a community-based institution established under the Government of Malawi with African Development Bank (ADB) support to enhance safe, sustainable, and reliable water access in communities.', help_text='Hero paragraph description'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_subtitle',
            field=models.CharField(default='Good and Quality Water for All', help_text='Hero subtitle (h2)', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_title',
            field=models.CharField(default='Nkula Water Users Association (WUA)', help_text='Main hero heading', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_title_highlight',
            field=models.CharField(default='Good and Quality Water for All', help_text='Highlighted text in hero (span)', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='location_address',
            field=models.CharField(default='Matandika Village, T/A Nkula, Machinga District, Malawi', help_text='Physical address', max_length=300),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='location_description',
            field=models.TextField(default='We serve multiple villages through our managed schemes and catchment areas.', help_text='Location description'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='location_subtitle',
            field=models.CharField(default='Where We Operate', help_text='Location section subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='location_title',
            field=models.CharField(default='Our Location', help_text='Location section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='mission_text',
            field=models.TextField(default='Empowering the community, promoting good health, and adapting and mitigating the effects of climate change through sustainable water management.', help_text='Mission statement'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='projects_intro',
            field=models.TextField(default='Nkula WUA is committed to improving water availability and sustainability by supporting:', help_text='Projects intro text'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='projects_items',
            field=models.TextField(default='Water scheme rehabilitation\nCommunity capacity building\nWater point monitoring\nHygiene and sanitation awareness\nCatchment protection programs', help_text='Project items (one per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='projects_outro',
            field=models.TextField(default='We believe safe water is the foundation of a healthy and productive community.', help_text='Projects closing text'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='projects_subtitle',
            field=models.CharField(default='Our Progress', help_text='Projects section subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='projects_title',
            field=models.CharField(default='Projects & Achievements', help_text='Projects section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='site_name',
            field=models.CharField(default='Nkula WUA', help_text='Site name shown in navbar', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='values_text',
            field=models.TextField(default='Transparency and Accountability\nHonesty\nTeamwork', help_text='Core values (one per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='vision_subtitle',
            field=models.CharField(default='Our guiding principles', help_text='Vision section subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='vision_text',
            field=models.TextField(default='Good and quality water for all.', help_text='Vision statement'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='vision_title',
            field=models.CharField(default='Vision, Mission & Values', help_text='Vision section title', max_length=100),
        ),
    ]
