# Generated by Django 5.2.3 on 2026-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0018_landingpagesettings_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesettings',
            name='gallery_subtitle',
            field=models.CharField(default='Photos of water infrastructure, intakes, pipes, and field work', help_text='Gallery subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='gallery_title',
            field=models.CharField(default='Gallery', help_text='Gallery section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='meeting_objectives_intro',
            field=models.TextField(default='Our regular meetings are aimed at:', help_text='Meeting intro text'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='meeting_objectives_items',
            field=models.TextField(default='Discussing ways to improve the performance of water schemes\nReviewing completed activities\nIdentifying challenges faced in the schemes\nPlanning solutions and community action strategies', help_text='Meeting objective items (one per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='meeting_objectives_subtitle',
            field=models.CharField(default='Our Regular Meeting Goals', help_text='Meeting Objectives subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='meeting_objectives_title',
            field=models.CharField(default='Meeting Objectives', help_text='Meeting Objectives section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='news_content',
            field=models.TextField(default='Meeting announcements\nScheme maintenance updates\nCommunity sanitation campaigns\nTraining and awareness programs', help_text='News items (one per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='news_intro',
            field=models.TextField(default='Stay updated with the latest activities and announcements from Nkula WUA.', help_text='News intro text'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='news_subtitle',
            field=models.CharField(default='Latest Updates', help_text='News section subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='news_title',
            field=models.CharField(default='News & Updates', help_text='News section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='schemes_list',
            field=models.TextField(default='Mangale Scheme|Serving communities with reliable water access\nNkala Scheme|Managed water infrastructure for local villages\nDodza Scheme|Sustainable water solutions for the community\nMilala Scheme|Clean water access for thousands of residents', help_text='Schemes (name|description per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='schemes_subtitle',
            field=models.CharField(default='Schemes and Catchment Areas', help_text='Schemes subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='schemes_title',
            field=models.CharField(default='Our Water Schemes', help_text='Schemes section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='villages_list',
            field=models.TextField(default="Mangale Scheme|GVH Lipongo,Ndanje,Maoni,M'balaka\nNkala Scheme|GVH Chingoli,Nthipo\nDodza Scheme|GVH Mtambo,Masanjala\nMilala Scheme|GVH Mkalawire,Mpango,Chimwayi,Mlawe", help_text='Villages grouped by scheme (scheme|village1,village2 per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='villages_subtitle',
            field=models.CharField(default='Communities Served', help_text='Villages subtitle', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='villages_title',
            field=models.CharField(default='Villages Under Nkula WUA', help_text='Villages section title', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='water_sources_images',
            field=models.TextField(default='intake.png|Water Intake System\nintake 3.png|Intake Infrastructure\npipes.png|Water Distribution Pipes\npulmbers.png|Plumbers at Work\nplumbers survey.png|Survey Work\nmilala survey.png|Milala Scheme Survey', help_text='Image file names and captions (filename|caption per line)'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='water_sources_subtitle',
            field=models.TextField(default='Water infrastructure and natural sources sustaining our communities', help_text='Water Sources subtitle'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='water_sources_title',
            field=models.CharField(default='Our Water Sources', help_text='Water Sources section title', max_length=100),
        ),
    ]
