# Generated by Django 5.2.3 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0021_deletedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='tap_installed_date',
            field=models.DateField(blank=True, help_text='Date when tap was installed', null=True),
        ),
    ]
