# Generated by Django 5.2.3 on 2026-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0022_add_tap_installed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Date when beneficiary was last activated', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Date when beneficiary was last deactivated', null=True),
        ),
    ]
