# Generated by Django 5.2.3 on 2026-05-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0023_add_activation_deactivation_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='deactivated_at',
        ),
        migrations.CreateModel(
            name='BeneficiaryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='accounting_app.beneficiary')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
