# Generated by Django 5.2.3 on 2026-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0024_add_beneficiary_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary_profiles/'),
        ),
    ]
