# Generated by Django 5.2.3 on 2026-05-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0025_beneficiary_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice number, payment reference, etc.', max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount added (invoice/bill)', max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted (payment)', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this transaction', max_digits=12)),
                ('fiscal_year', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='accounting_app.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Balance histories',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
    ]
