# Generated by Django 5.2.3 on 2026-06-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0027_systemversion_datamigrationlog_systemupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('private', 'Private'), ('communal', 'Communal'), ('town', 'Town')], default='private', max_length=20),
        ),
    ]
