# Generated by Django 5.2.3 on 2026-05-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_app', '0021_deletedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting_app.landingpagesettings',),
        ),
    ]
